spring:
  datasource:
    # mysql数据源
    name: mysql
    url: jdbc:mysql://localhost:3306/demodb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
